# Generated by Django 4.2 on 2026-05-10 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_products_registered', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_products_donated', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_products_sold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_products_expired', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_weight_rescued', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_weight_donated', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_weight_sold', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_transactions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_users', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('active_users', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Statistics',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_name', models.CharField(max_length=100)),
                ('total_food_rescued_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_co2_avoided_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_water_saved_liters', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_energy_saved_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('people_fed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('families_supported', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_value_rescued', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Environmental Impact',
                'verbose_name_plural': 'Environmental Impacts',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='LocationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products_handled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_weight_rescued', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_products_per_day', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_customers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('repeat_customers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_co2_saved', models.FloatField(default=0, help_text='in kg', validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_water_saved', models.FloatField(default=0, help_text='in liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Metrics',
                'verbose_name_plural': 'Location Metrics',
            },
        ),
        migrations.CreateModel(
            name='PartnerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products_donated', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_weight_donated', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_donation_per_day', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_products_sold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_revenue_from_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lives_impacted', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_waste_prevented', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Metrics',
                'verbose_name_plural': 'Partner Metrics',
            },
        ),
        migrations.CreateModel(
            name='UserActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchases', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_donations_received', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_weight_received', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_active', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('co2_saved_through_purchases', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Activity Report',
                'verbose_name_plural': 'User Activity Reports',
            },
        ),
    ]
