# Generated by Django 4.2 on 2026-05-10 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivityreport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnermetrics',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.businesspartner'),
        ),
        migrations.AddField(
            model_name='locationmetrics',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.location'),
        ),
    ]
