# Generated by Django 4.2 on 2026-05-10 03:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('commercial_center', 'Centro Comercial'), ('restaurant', 'Restaurante'), ('supermarket', 'Supermercado'), ('cafe', 'Café'), ('other', 'Otro')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'Mantenimiento'), ('inactive', 'Inactivo')], default='active', max_length=20)),
                ('total_compartments', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_compartments', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_temperature', models.FloatField(blank=True, null=True)),
                ('refrigeration_power', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.location')),
            ],
            options={
                'verbose_name': 'Smart Device',
                'verbose_name_plural': 'Smart Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('restaurant', 'Restaurante'), ('supermarket', 'Supermercado'), ('cafe', 'Café'), ('bakery', 'Panadería'), ('market', 'Mercado'), ('other', 'Otro')], max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.location')),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupado'), ('maintenance', 'Mantenimiento'), ('error', 'Error')], default='available', max_length=20)),
                ('current_temperature', models.FloatField(blank=True, null=True)),
                ('temperature_setpoint', models.FloatField(default=4.0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='core.smartdevice')),
            ],
            options={
                'verbose_name': 'Compartment',
                'verbose_name_plural': 'Compartments',
                'ordering': ['device', 'compartment_number'],
                'unique_together': {('device', 'compartment_number')},
            },
        ),
    ]
