# Generated by Django 4.2 on 2026-05-10 03:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('mobile_payment', 'Pago Móvil'), ('transfer', 'Transferencia')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('withdrawal_code', models.CharField(max_length=50, unique=True)),
                ('withdrawal_code_used', models.BooleanField(default=False)),
                ('withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('compartment_open', 'Apertura de Compartimiento'), ('code_validation', 'Validación de Código'), ('compartment_close', 'Cierre de Compartimiento'), ('error', 'Error')], max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('withdrawal_code', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.smartdevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Interaction',
                'verbose_name_plural': 'Device Interactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_collection_date', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_code', models.CharField(blank=True, max_length=50)),
                ('code_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='core.smartdevice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='products.product')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer', '-created_at'], name='transaction_buyer_i_053873_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_4b1739_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['withdrawal_code'], name='transaction_withdra_9a2d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_e7c1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['product', 'status'], name='transaction_product_159abf_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['expiration_date'], name='transaction_expirat_3db28b_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinteraction',
            index=models.Index(fields=['device', '-timestamp'], name='transaction_device__57069f_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinteraction',
            index=models.Index(fields=['user', '-timestamp'], name='transaction_user_id_38829c_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_10180c_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['product', 'status'], name='transaction_product_c20d88_idx'),
        ),
    ]
