# Generated by Django 4.2 on 2026-05-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_populate_lockers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='locker',
            name='transactions_locker_numero_idx',
        ),
    ]
